version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    command: npm start

  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: name_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

volumes:
  db-data:

networks:
  overlay:
