---
  # Ansible documentation on EC2:
  # http://docs.ansible.com/ec2_module.html
- name: Provision an EC2 node
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning
  vars:
    instance_name: metisa
    instance_type: t2.small
    security_group: default
    image: ami-96f1c1c4
    region: ap-southeast-1
    keypair: altitudelabs
  tasks:
    - name: Launch new instance
      local_action: ec2 instance_tags="Name={{ instance_name }}" group={{ security_group }} instance_type={{ instance_type}} image={{ image }} wait=true region={{ region }} keypair={{ keypair }}
      register: ec2
      # "

    - name: Add instance to web servers
      lineinfile: dest="./production" regexp="\[webservers\]" insertafter="[webservers]" line="[webservers]\n{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
      with_items: ec2.instances
      # "

    - name: Add instance to db servers
      lineinfile: dest="./production" regexp="\[dbservers\]" insertafter="[dbservers]" line="[dbservers]\n{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
      with_items: ec2.instances
      # "

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
